### ISSUE TITLE
[Request] Print tabs before the model

### ISSUE THREAD

**Issue by domgregori** [5axes/SpoonAntiWarping#6]
Is it possible to have the spoon tabs printed first, before the model? Not sure if plug-ins allow you to do that, so maybe with a Post Processing plug-in?

**Comment by 5axes** [comment]
I don't think we can change succesfuly the printing order via a plugin. But a postprocessing script using the default name could be a solution. But in this case it will be necessar to be in relative extrusion mode.

**Comment by domgregori** [comment]
Tried it out but doesn't seem to change anything. In the log I am seeing that it runs with no errors. I'm including a diff file between gcode with no SpoonOrder and with SpoonOrder post processing. 
[gcode_diffed.txt](https://github.com/5axes/SpoonAntiWarping/files/10959781/gcode_diffed.txt)

**Comment by 5axes** [comment]
**Layer Analyse** must be at least equal to 1 ?

![image](https://user-images.githubusercontent.com/11015345/224777920-d229d543-d729-4501-9774-8ead469d2c3d.png)

**Comment by domgregori** [comment]
Yep, I have Layer Analyse set to 1 and the tabs are only on the first layer. Tried manually typing in 1 as well and doesn't seem to change anything.

**Comment by 5axes** [comment]
Download the Last release of the code .. Should be OK

**Comment by 5axes** [comment]
> Quick question, what editor are you using that has folding for gcode?

Notepad++
