### ISSUE TITLE
Drop model does not work (bug ?)

### ISSUE THREAD

**Issue by yet-another-average-joe** [5axes/SpoonAntiWarping#7]
None of "drop down model" (Move" button) or "Automatically drop model to the buildplate" (Preferences) has effect on the tabs. 

BTW, couldn't the tabs be created with a preset pattern ? Or a patternzs drop down list be in the button dialog box ? IMO, the easiest one is concentric because we don't have to bother with pattern orientation, and it is the most "isotropic" (but not sure : the easiest does not necessarily mean the best !)

**Comment by 5axes** [comment]
Tabs are linked to the Part, so it looks like normal that you cannot drop them on the buildplate . Not sure to really understand your question.

**Comment by yet-another-average-joe** [comment]
Tabs can be moved , resized, etc.
But they can be moved vertically, and printed in thin air ; shouldn't they always have their Z attribute set/reset or locked to zero ?

Here's an airbourne spoon :

![Airbourne Spoon](https://user-images.githubusercontent.com/43514870/233069468-c3ca08d6-ad7b-417d-9f8a-d822430fbdc0.PNG)

It takes off, but does not auto lands, while the model itself does. Discovered this behaviour after printing one in thin air, one or two millimeter above the bed ; verified the coords, one thasn't on the plate. Most likely after I accidentally moved it using the wrong handle.

**Comment by 5axes** [comment]
Yes you're right it's a Cura Limitation. I cannot do anything on this point.

**Comment by yet-another-average-joe** [comment]
There's another weird behaviour. Select a tab, right click, multiply it (1 = duplicate). It is created at +2.5 mm.

**Comment by 5axes** [comment]
Normal it's not designed to be multiply. It's not a plugin problem but a cura upstream issue. If you do the same manualy with a support blocker you have the same result.
![UltiMaker-Cura_emFWUPDP55](https://user-images.githubusercontent.com/11015345/233165874-e1136e66-4efa-42b3-91d7-2f20def616f2.gif)
